# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8lvUX3A24FtdsnLjTQQQ2CAhgyQBh5m
"""

import pandas as pd
api="https://alivecore360.com/api/livesearch/v5?key=15d273cc-0b8a-4460-9cd8-55fa55a3e1c1&Twitter_handler=HSBC&lang=en&optional_connectors=livesearch&days=10&type=detailed&interval=day"
import requests
 
# Making a get request
api_data = requests.get(api).json()
#print(api_data)
#print(type(api_data))
samples=[]


for k in api_data["data"]["twitter"]["data"]:
  samples.append(k["tweet"])
#print(samples)
x = pd.Series(samples)
x.to_excel("HSBC2.xlsx") #to_csv for .csv



